import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header/header";
import QueryProviders from "./providers/tan-stack/query-provider";
import UserContextProvider from "./providers/user-provider/user-provider";
import { Toaster } from 'sonner';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Trip Planner App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProviders>
          <UserContextProvider>
            <Header />
            {children}
            <Toaster position="top-center" richColors/>
          </UserContextProvider>
        </QueryProviders>
      </body>
    </html>
  );
}
